"""Authored 16px inventory sprites with stepped material palettes and no antialiasing.

These native pixel patterns are the editable source, not resized illustrations.
Vanilla item textures were inspected for silhouette scale, diagonal tools, stepped
glass highlights, wood grain, iron bevels and top-left light direction.
"""
from PIL import Image


def raster(pattern, palette):
    rows = pattern.strip('\n').splitlines()
    assert len(rows) <= 16
    image = Image.new('RGBA', (16, 16))
    for y, row in enumerate(rows):
        assert len(row) <= 16, (y, row)
        for x, pixel in enumerate(row):
            if pixel != '.':
                image.putpixel((x, y), tuple(bytes.fromhex(palette[pixel].lstrip('#'))) + (255,))
    return image


GLASS = {'o':'466779','n':'749CAE','g':'A7C8D5','h':'D9EDF0','w':'F4F5DF',
         'c':'7C4930','C':'BC7850','L':'E3A07A','s':'DEE0BF','S':'F7F4D6','d':'ADA88A','b':'7E846E'}
SALTS = """
................
.....cCCCCc.....
.....cCLLCc.....
......oggo......
.....ohggno.....
....ohhgggno....
...ohhhggggno...
..ohhSSsSsdgno..
..ohSSSSsssdno..
..ohSsSsSssbno..
..ohSsSSsssddo..
..onssssssddno..
...ongdddggno...
....onnggnno....
.....oooooo.....
................
"""
TONIC = """
................
......cCCc......
......cLLc......
......ohgo......
......ohno......
.....ohhgno.....
....ohhgggno....
...ohhSSssgno...
..ohhSSssddgno..
..ohSSssdddano..
..ohSssddadano..
..onssddaaaano..
...ogddaaagno...
....ongggnno....
.....oooooo.....
................
"""
BANDAGE = """
................
................
........ooooo...
......ooHHhho...
....ooHHhhmmoo..
...oHHhhmmHHmo..
..oHHhmmHddHmo..
..oHhhmmHdodmo..
..ohhmmmdoodmo..
..ohmmmmHddmbo..
..ommmmbmmmbbo..
...ombbbbbboo...
....ooooooo.....
................
................
................
"""
LINEN = {'o':'665C50','H':'F3F0DE','h':'DDD8C3','m':'B8B5A1','b':'8B8B7D','d':'7D796A'}
MUG = """
................
....s.....s.....
.....S...S......
....s...s.......
.....oooooo.....
...ooHHHHhmoo...
..oHhcccbbmdno..
..oHhbbbbbmdnon.
..oHHhhmmmdnonon
..oHHhmmmmmnonon
..oHHhmmmmdnonon
..ohhmmmdddnono.
...ohmmdddbooo..
....obbbboo.....
.....oooo.......
................
"""
CERAMIC = {'o':'5A4433','n':'A47B57','H':'F1DEC0','h':'DABC91','m':'B89468','d':'8D6B49','b':'59402D','c':'8F5A31','s':'A4B1A9','S':'E1E7D5'}
BREAD = """
................
.........ooo....
.......ooaaao...
......oaHHHaao..
.....oaHhHhmao..
....oaHhammhbao.
...oaHhHhahmbao.
..oaHhHhamhmbao.
..oHhHhahmmbao..
.oHhHhamhmbaoo..
.oHhahmmmbbao...
.oahmmmbbboo....
..ombbbboo......
...ooooo........
................
................
"""
WHEAT = {'o':'594117','a':'9D7428','H':'D5AD49','h':'C49735','m':'AC7E22','b':'76521C'}
STEW = """
................
................
................
......oooo......
...oooHHhhooo...
..oHhhaaPahhho..
.oHhGaPPrraamho.
.oHhaaGarrGaaho.
.omHhhhaaahhhmo.
..ommmHHhhmmoo..
...obmmmmmboo...
....obbbbboo....
.....oooooo.....
................
................
................
"""
SOUP = {'o':'4D341E','H':'BB925D','h':'A87B43','m':'885D2F','b':'684722','a':'B77534','P':'E6C979','r':'D29041','G':'628344'}
BROOM = """
.............oo.
............oWo.
...........oWwo.
..........oWwo..
.........oWwo...
........oWwo....
.......oWwo.....
......oWwo......
.....ooao.......
....obBao.......
...oHHbbmo......
..oHhhmbbmo.....
.oHhhmmbbmo.....
oHhhmmmbboo.....
ohmmmbbooo......
.oooooo.........
"""
STRAW = {'o':'534321','H':'D3BE65','h':'BDA451','m':'A68A37','b':'816827','a':'79562C','B':'AE7940','W':'B79559','w':'805C30'}
BRUSH = """
................
............oo..
..........ooHho.
.........oHHhho.
........oHHhmoo.
.......oHhhmbo..
.......oghmbbo..
.......onnmbo...
......omgnoo....
.....oamo.......
....oamo........
...oamo.........
..oamo..........
.oamo...........
.ooo............
................
"""
BRISTLE = {'o':'5A4230','H':'E7D1AA','h':'D4B991','m':'AF926F','b':'577D91','g':'D6D8CB','n':'8D9897','a':'A87B40'}
HAMMER = """
................
.........ooo....
.......ooHHmo...
......oHHHHmmo..
.....oHHhmmdbo..
.....oHhmmdbbo..
......ommdboo...
.......obboo....
......oamo......
.....oamo.......
....oamo........
...oamo.........
..oamo..........
.oamo...........
.ooo............
................
"""
IRON = {'o':'3E3B35','H':'E4E5DD','h':'B8C0BE','m':'929D9A','d':'697572','b':'535B57','a':'A88545'}
LUTE = """
............oo..
...........oHHmo
...........omhbo
..........oahoo.
.........oaho...
........oaho....
.....ooooaho....
....oaHHahbo....
...oaHhhahmbo...
..oaHhhbobhmbo..
..oHhhboobhmbbo.
..oHhhhoohmmbbo.
..oahhhahmmmbbo.
...oahammmbboo..
....obbbbboo....
.....ooooo......
"""
LUTHIER = {'o':'503622','H':'DBB06A','h':'C4944E','m':'A77A38','b':'7D5328','a':'E0CC8F'}
JOURNAL = """
................
.......oooo.....
.....ooaaaao....
...ooaHHhaaho...
..oaHHhhhaahho..
.oaHHhhhaahhboo.
.oahhhhaahhbooPo
.obahhaahhbooPPo
.obbaahhbooPPPbo
.obbabbooPPPbbbo
.obbbooPPPbbboo.
..ooPPPbbbooo...
...obbbooo......
....ooo.........
................
................
"""
PAPER = {'o':'413622','a':'8D6B39','H':'BB9954','h':'A5823D','b':'664B29','P':'D8D2AB'}

# Chestplate-sized silhouettes: actual cloth/metal volume rather than tiny flat shirts.
UNIFORM = """
................
................
.oooo......oooo.
oHhmo......ohmbo
oHHhmo....ohmmbo
ohHHhmottohmmdbo
.ohHhmtTtmmdbo..
..ohhmmtmmdbo...
...ohhmTmmdbo...
...ohhmmmmdbo...
...ohhmmmmdbo...
...omttTttdbo...
...ohmmmmddbo...
...ommmmddbbo...
....ooooooo.....
................
"""

# Separate palettes use warm material outlines, colored shadows and small highlights.
GARMENTS = {
 'knight':       ('343C42','D8DFDA','ABBDBF','7B9299','576C76','42555D','A48944','E1C369'),
 'archer':       ('283D30','8AAA70','6B9258','4D7444','365736','293F2B','7C5934','D0A76E'),
 'cook':         ('514D40','FFFADE','E7E1C8','C7C9B5','9AA698','778A81','9A4235','C57256'),
 'tavern_keeper':('413123','C28C4B','AA7440','89542F','693D28','4E2C21','D7C4A0','F3E4BE'),
 'apothecary':   ('2D463C','DCE4C7','A2C4A1','72A282','4F7C65','3C6251','D4CAB0','F3E9D4'),
 'painter':      ('4A3A2B','E8D6AA','D7BD89','B99B6B','957B53','75603E','426D85','75A1AA'),
 'bard':         ('3F2842','C17EA0','A3658D','824E76','603959','4D2C47','B3944C','EAD288'),
 'tailor':       ('273D46','9BBDC2','72A3AD','4E8897','386773','2B505F','C7C6A9','F0E6BE'),
 'carpenter':    ('493421','D7AA63','BD8B46','9D7034','785129','5E3D22','7D8C8C','BCC5BA'),
 'scholar':      ('362C40','A290AD','887093','6B547C','503D62','3F2F4D','B89D63','E1C889'),
}


def uniform(job):
    image = raster(UNIFORM, dict(zip('oHhmdbtT', GARMENTS[job])))
    colors = {k:tuple(bytes.fromhex(v))+(255,) for k,v in dict(zip('oHhmdbtT',GARMENTS[job])).items()}
    def pixel(x,y,s):image.putpixel((x,y),colors[s])
    # Job details are placed on the chest and respect its existing shaded silhouette.
    if job == 'knight':
        for x,y in [(4,7),(11,7),(5,12),(10,12)]:pixel(x,y,'H')
        for y in range(7,11):pixel(8,y,'h');pixel(9,y,'d')
    elif job == 'archer':
        for x,y in [(5,6),(6,7),(7,8),(8,9),(9,10),(10,11)]:pixel(x,y,'t')
    elif job == 'cook':
        for x in range(5,11):pixel(x,8,'H');pixel(x,9,'h')
        for y in range(10,14):pixel(6,y,'H');pixel(9,y,'h')
    elif job == 'tavern_keeper':
        for y in range(7,11):pixel(7,y,'T');pixel(8,y,'t')
        pixel(9,9,'H')
    elif job == 'apothecary':
        for y in range(8,11):pixel(8,y,'T')
        for x in range(7,10):pixel(x,9,'T')
    elif job == 'painter':
        pixel(6,8,'T');pixel(6,9,'t');pixel(10,10,'t');pixel(9,10,'T');pixel(5,12,'H')
    elif job == 'bard':
        for x in range(5,11):pixel(x,12,'t')
        for x,y in [(5,8),(6,9),(9,9),(10,8)]:pixel(x,y,'T')
    elif job == 'tailor':
        for x in range(6,10):pixel(x,10,'t')
        pixel(6,9,'T');pixel(9,9,'T');pixel(8,7,'H')
    elif job == 'carpenter':
        for x in range(5,8):pixel(x,9,'d');pixel(x,10,'b')
        pixel(9,9,'T');pixel(9,10,'t')
    elif job == 'scholar':
        for x in range(8,11):pixel(x,8,'t');pixel(x,9,'T');pixel(x,10,'t')
    return image


CLOAK = """
................
.....oooooo.....
....oHHhmmoo....
....ohmdddbo....
...ohmmdddbbo...
..ohHHhmmdddbo..
..oHhHhmmdmdbo..
.oHHhHhmmdmddbo.
.oHhhHhmmdmddbo.
oHHhhHhmmdmmdbbo
oHhhhHhmmdmmdbbo
oHhhHhhmmdmmdbbo
ohhhHhhmmdmmdbbo
.omtTttttTtddbo.
..oooooooooooo..
................
"""
PONCHO = """
................
......oooo......
.....oHHhmo.....
....oHhddmbo....
....ohdoobbo....
...oHHhmmddbo...
..oHHhmttmddbo..
.oHHhmmTTmmddbo.
.oHhhmmttmmddbo.
oHHhhmmttmmmdbbo
ohhhmmmtTmmmdbbo
ohhmmmttTtmmdbbo
omttTttTTtttTdbo
.obmmmtTmmddbbo.
..oooooooooooo..
................
"""


def item_sprite(name):
    if name.endswith('_uniform'):return uniform(name.removesuffix('_uniform'))
    if name == 'rain_cloak':return raster(CLOAK, dict(zip('oHhmdbtT',('263C43','8CA8AE','608A95','467483','335D6D','264652','5B7771','BAC4A3'))))
    if name == 'hooded_poncho':return raster(PONCHO, dict(zip('oHhmdbtT',('514023','E3CA82','CDB269','B0924A','8A7138','6B562C','925C39','D79A67'))))
    if name == 'smelling_salts':return raster(SALTS,GLASS)
    if name == 'revival_tonic':return raster(TONIC,dict(GLASS,s='558558',S='91BA7F',d='39634C',a='294E43'))
    if name == 'bandage_wrap':return raster(BANDAGE,LINEN)
    if name == 'steaming_coffee_mug':return raster(MUG,CERAMIC)
    if name == 'empty_coffee_mug':
        pattern=MUG.splitlines()
        pattern[2]='................';pattern[3]='................';pattern[4]='................'
        return raster('\n'.join(pattern),dict(CERAMIC,c='7E6245',b='6B523A'))
    if name == 'fresh_village_bread':return raster(BREAD,WHEAT)
    if name == 'hearty_stew':return raster(STEW,SOUP)
    if name == 'broom':return raster(BROOM,STRAW)
    if name == 'paintbrush':return raster(BRUSH,BRISTLE)
    if name == 'carpenter_hammer':return raster(HAMMER,IRON)
    if name == 'lute':return raster(LUTE,LUTHIER)
    if name == 'field_journal':return raster(JOURNAL,PAPER)
    raise ValueError('No authored sprite: '+name)
