"""Village social life assets: emote bubbles and the Village Ledger.

Writes
  assets/villagefriends/textures/gui/emotes.png   speech bubbles (32px cells, row 0) and emote symbols
                                                  (16px cells from y=32), shared by the world and the UI
  assets/villagefriends/textures/item/village_ledger.png and its item model and definition
  data/villagefriends/recipe/village_ledger.json  book + ink sac + paper

Symbols are authored as fill masks; a dark outline is added around each shape automatically, so a
symbol reads at any distance. Run from the repository root:

  python tools/social_assets.py            write everything
  python tools/social_assets.py --preview  also write build/previews/emotes_preview.png (8x)
"""
import json
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
from item_sprites import raster  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), '..', 'src', 'main', 'resources')
ASSETS = os.path.join(ROOT, 'assets', 'villagefriends')
NS = 'villagefriends'

# Order matches dev.villagefriends.Emote; DOTS uses three frames.
SYMBOLS = ['EXCLAIM', 'QUESTION', 'HEART', 'NOTE', 'ANGER', 'SWEAT', 'DOTS1', 'DOTS2',
           'DOTS3', 'SLEEP', 'SPARKLE', 'IDEA', 'GLOOM', 'BLUSH']

FILLS = {
    'EXCLAIM': ("""
................
................
......rrrR......
......rrrR......
......rrRR......
......rrRR......
.......rRR......
.......rR.......
.......rR.......
................
................
......rrRR......
......rRRR......
................
................
................
""", {'r': 'FF7A5C', 'R': 'E2412F'}, '5A1A12'),
    'QUESTION': ("""
................
................
.....bbbbbB.....
....bbbBBBBB....
....bB....BB....
..........BB....
.........bBB....
........bBB.....
.......bBB......
.......bB.......
................
................
.......bBB......
.......BBB......
................
................
""", {'b': '8CC8FF', 'B': '3A86E0'}, '16305A'),
    'HEART': ("""
................
................
................
...hhp....hpp...
..hhppp..pppPP..
..hppppppppppP..
..ppppppppppPP..
..pppppppppPPP..
...pppppppPPP...
....pppppPPP....
.....ppPPPP.....
......pPPP......
.......PP.......
................
................
................
""", {'h': 'FFD0DC', 'p': 'FF6A92', 'P': 'D83A6C'}, '5A1430'),
    'NOTE': ("""
................
................
........m.......
........mm......
........mMm.....
........m.Mm....
........m..M....
........m..M....
........m.......
........m.......
.....mmmm.......
....mmmmMM......
....mMMMMM......
.....MMMM.......
................
................
""", {'m': 'C3A0FF', 'M': '7D52E8'}, '2A1858'),
    'ANGER': ("""
................
................
.....rR....Rr...
.....rR....Rr...
.....rR....Rr...
..rrrRR....RRrr.
..RRRR......RRR.
................
................
..rrrr......rrr.
..RRRRR....RRRR.
.....rR....Rr...
.....rR....Rr...
.....rR....Rr...
................
................
""", {'r': 'FF8A7A', 'R': 'E5392F'}, '5C1410'),
    'SWEAT': ("""
................
................
.......w........
.......ww.......
......wbbb......
......wbbb......
.....wbbbbB.....
.....wbbbbB.....
....wwbbbbBB....
....wbbbbbBB....
....bbbbbbBB....
.....bbbBBB.....
......BBBB......
................
................
................
""", {'w': 'EAF7FF', 'b': '7CC8FF', 'B': '3A8ED6'}, '163A5E'),
    'DOTS1': ("""
................
................
................
................
................
................
.ddd............
.dDD............
.dDD............
................
................
................
................
................
................
................
""", {'d': '8A776A', 'D': '4F4038'}, '2B211C'),
    'SLEEP': ("""
................
.........zzzz...
...........z....
..........z.....
.........zzzz...
................
.zzzzzz.........
.....zZ.........
....zZ..........
...zZ...........
..zZ............
.zzzzzZ.........
................
................
................
................
""", {'z': 'B5D3FF', 'Z': '6F9BE6'}, '1D2D55'),
    'SPARKLE': ("""
................
................
.......y........
.......y........
......yYy.......
......yYy.......
...yyyyYYYYY....
.....yYYYY......
......yYY.......
......yYY.......
.......Y........
.......Y.....y..
............yYy.
.............y..
................
................
""", {'y': 'FFF2A8', 'Y': 'F2C230'}, '5A4210'),
    'IDEA': ("""
................
................
......yyyY......
.....yyyyyY.....
....yyyyyyYY....
....yyhyyyYY....
....yyhyyyYY....
....yyyyyyYY....
.....yyyyYY.....
......yyYY......
......gggG......
......ggGG......
.......GG.......
................
................
................
""", {'y': 'FFF0A0', 'Y': 'F0BE2E', 'h': 'FFFFFF', 'g': 'C8C8C8', 'G': '8C8C8C'}, '4E3A10'),
    'GLOOM': ("""
................
................
.....cccC.......
...cccccCC......
..ccccccccCC....
.ccccccccccCC...
.cCCCCCCCCCCC...
................
...b....b.......
..bB...bB...b...
.......b...bB...
....b...........
...bB...........
................
................
................
""", {'c': 'C9CED6', 'C': '8C94A3', 'b': '8CC8FF', 'B': '3A86E0'}, '262B36'),
    'BLUSH': ("""
................
................
..pp.pp.........
.ppppppP........
.pppppPP........
..pppPP.........
...pPP..........
....P....pp.pp..
........ppppppP.
........pppppPP.
.........pppPP..
..........pPP...
...........P....
................
................
................
""", {'p': 'FF8FB0', 'P': 'E04E7E'}, '5A1430'),
}


def mask_image(pattern, palette, outline, size=16):
    """Rasters a fill pattern and rings every filled shape with a one-pixel outline."""
    rows = pattern.strip('\n').splitlines()
    image = Image.new('RGBA', (size, size))
    filled = set()
    for y, row in enumerate(rows):
        for x, pixel in enumerate(row):
            if pixel != '.':
                image.putpixel((x, y), rgba(palette[pixel]))
                filled.add((x, y))
    for (x, y) in filled:
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                n = (x + dx, y + dy)
                if n not in filled and 0 <= n[0] < size and 0 <= n[1] < size and image.getpixel(n)[3] == 0:
                    image.putpixel(n, rgba(outline))
    return image


def rgba(hex_color, alpha=255):
    return tuple(bytes.fromhex(hex_color)) + (alpha,)


def dots(frame):
    pattern = FILLS['DOTS1'][0].strip('\n').splitlines()
    rows = [list(r) for r in pattern]
    for i in range(1, frame):
        for y in range(6, 9):
            for x in range(1, 4):
                rows[y][x + i * 5] = rows[y][x]
    return '\n'.join(''.join(r) for r in rows)


def bubble(kind):
    """A 32px bubble: round speech, a puffy thought cloud, or a spiky shout."""
    size = 32
    inside = set()
    if kind == 'speech':
        for y in range(3, 23):
            for x in range(3, 29):
                cx = min(max(x, 8), 23)
                cy = min(max(y, 8), 17)
                if (x - cx) ** 2 + (y - cy) ** 2 <= 25:
                    inside.add((x, y))
        for y in range(23, 28):
            for x in range(12, 12 + (28 - y)):
                inside.add((x - (y - 23) // 2, y))
    elif kind == 'thought':
        for (cx, cy, r) in [(10, 12, 7), (16, 9, 7), (22, 12, 7), (16, 16, 7), (9, 17, 4.5), (23, 17, 4.5)]:
            for y in range(32):
                for x in range(32):
                    if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                        inside.add((x, y))
        for (cx, cy, r) in [(12, 25, 2.2), (9, 29, 1.4)]:
            for y in range(32):
                for x in range(32):
                    if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                        inside.add((x, y))
    else:  # shout: a starburst with even spikes
        import math
        for y in range(32):
            for x in range(32):
                dx, dy = x - 15.5, (y - 13) * 1.15
                angle = math.atan2(dy, dx)
                radius = 11 + 2.6 * math.cos(angle * 9)
                if dx * dx + dy * dy <= radius * radius:
                    inside.add((x, y))
        for y in range(22, 29):
            for x in range(11, 11 + max(1, (29 - y) // 2 + 1)):
                inside.add((x - (y - 22) // 2, y))
    image = Image.new('RGBA', (size, size))
    paper, shade, ink = 'FFFBF2', 'EADCC4', '3B2A20'
    for (x, y) in inside:
        edge_shade = (x + 1, y + 1) not in inside or (x + 2, y + 2) not in inside
        image.putpixel((x, y), rgba(shade if edge_shade else paper))
    for (x, y) in inside:
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                n = (x + dx, y + dy)
                if n not in inside and 0 <= n[0] < size and 0 <= n[1] < size:
                    image.putpixel(n, rgba(ink))
    return image


def emote_sheet():
    sheet = Image.new('RGBA', (128, 128))
    for i, kind in enumerate(['speech', 'thought', 'shout']):
        sheet.paste(bubble(kind), (i * 32, 0))
    for i, name in enumerate(SYMBOLS):
        if name.startswith('DOTS'):
            fill, palette, outline = FILLS['DOTS1']
            image = mask_image(dots(int(name[-1])), palette, outline)
        else:
            fill, palette, outline = FILLS[name]
            image = mask_image(fill, palette, outline)
        sheet.paste(image, ((i % 8) * 16, 32 + (i // 8) * 16))
    return sheet


LEDGER = """
................
..oooooooooooo..
..oRRRRRRRRRRpo.
..oRrrrrrrrrRpo.
..oRrGGGGGGrRpo.
..oRrGyyyyGrRpo.
..oRrGGGGGGrRpo.
..oRrrrrrrrrRpo.
..oRrhhhhhhrRpo.
..oRrrrrrrrrRpo.
..oRrhhhhhhrRpo.
..oRrrrrrrrrRpo.
..oRRRRRRRRRRpo.
..obbbbbbbbbbbo.
..oooooooooooo..
................
"""
LEDGER_COLORS = {'o': '3A2416', 'R': '7A3A26', 'r': '9E5233', 'G': 'C9A04A', 'y': 'F2D27A',
                 'h': 'C47A55', 'p': 'F3E6C8', 'b': 'D9C7A0'}


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(json.dumps(data, indent=2) + '\n')


def png(path, image):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    image.save(path)


def main():
    sheet = emote_sheet()
    png(os.path.join(ASSETS, 'textures', 'gui', 'emotes.png'), sheet)
    png(os.path.join(ASSETS, 'textures', 'item', 'village_ledger.png'), raster(LEDGER, LEDGER_COLORS))
    write(os.path.join(ASSETS, 'items', 'village_ledger.json'),
          {'model': {'type': 'minecraft:model', 'model': f'{NS}:item/village_ledger'}})
    write(os.path.join(ASSETS, 'models', 'item', 'village_ledger.json'),
          {'parent': 'minecraft:item/generated', 'textures': {'layer0': f'{NS}:item/village_ledger'}})
    write(os.path.join(ROOT, 'data', NS, 'recipe', 'village_ledger.json'),
          {'type': 'minecraft:crafting_shapeless', 'category': 'misc', 'result': {'id': f'{NS}:village_ledger', 'count': 1},
           'ingredients': ['minecraft:book', 'minecraft:ink_sac', 'minecraft:paper']})
    if '--preview' in sys.argv:
        preview = Image.new('RGBA', (128, 128), (110, 150, 90, 255))
        preview.alpha_composite(sheet)
        out = os.path.join(os.path.dirname(__file__), '..', 'build', 'previews', 'emotes_preview.png')
        png(out, preview.resize((1024, 1024), Image.NEAREST))
        print('preview', os.path.normpath(out))


if __name__ == '__main__':
    main()
